export const countries = [
	{ label: 'Афганистан', code: 'AF' },
	{ label: 'Албания', code: 'AL' },
	{ label: 'Алжир', code: 'DZ' },
	{ label: 'Американское Самоа', code: 'AS' },
	{ label: 'Андорра', code: 'AD' },
	{ label: 'Ангола', code: 'AO' },
	{ label: 'Ангилья', code: 'AI' },
	{ label: 'Аргентина', code: 'AR' },
	{ label: 'Армения', code: 'AM' },
	{ label: 'Аруба', code: 'AW' },
	{ label: 'Австралия', code: 'AU' },
	{ label: 'Австрия', code: 'AT' },
	{ label: 'Азербайджан', code: 'AZ' },
	{ label: 'Багамские Острова', code: 'BS' },
	{ label: 'Бахрейн', code: 'BH' },
	{ label: 'Бангладеш', code: 'BD' },
	{ label: 'Барбадос', code: 'BB' },
	{ label: 'Беларусь', code: 'BY' },
	{ label: 'Бельгия', code: 'BE' },
	{ label: 'Белиз', code: 'BZ' },
	{ label: 'Бенин', code: 'BJ' },
	{ label: 'Бутан', code: 'BT' },
	{ label: 'Боливия', code: 'BO' },
	{ label: 'Босния и Герцеговина', code: 'BA' },
	{ label: 'Ботсвана', code: 'BW' },
	{ label: 'Бразилия', code: 'BR' },
	{ label: 'Британская Территория в Индийском Океане', code: 'IO' },
	{ label: 'Бруней', code: 'BN' },
	{ label: 'Болгария', code: 'BG' },
	{ label: 'Буркина-Фасо', code: 'BF' },
	{ label: 'Бурунди', code: 'BI' },
	{ label: 'Камбоджа', code: 'KH' },
	{ label: 'Камерун', code: 'CM' },
	{ label: 'Канада', code: 'CA' },
	{ label: 'Кабо-Верде', code: 'CV' },
	{ label: 'Каймановы Острова', code: 'KY' },
	{ label: 'Центральноафриканская Республика', code: 'CF' },
	{ label: 'Чад', code: 'TD' },
	{ label: 'Чили', code: 'CL' },
	{ label: 'Китай', code: 'CN' },
	{ label: 'Остров Рождества', code: 'CX' },
	{ label: 'Кокосовые (Килинг) Острова', code: 'CC' },
	{ label: 'Колумбия', code: 'CO' },
	{ label: 'Коморы', code: 'KM' },
	{ label: 'Конго', code: 'CG' },
	{ label: 'Конго, Демократическая Республика', code: 'CD' },
	{ label: 'Острова Кука', code: 'CK' },
	{ label: 'Коста-Рика', code: 'CR' },
	{ label: 'Кот-д\'Ивуар', code: 'CI' },
	{ label: 'Хорватия', code: 'HR' },
	{ label: 'Куба', code: 'CU' },
	{ label: 'Кюрасао', code: 'CW' },
	{ label: 'Кипр', code: 'CY' },
	{ label: 'Чешская Республика', code: 'CZ' },
	{ label: 'Дания', code: 'DK' },
	{ label: 'Джибути', code: 'DJ' },
	{ label: 'Доминика', code: 'DM' },
	{ label: 'Доминиканская Республика', code: 'DO' },
	{ label: 'Эквадор', code: 'EC' },
	{ label: 'Египет', code: 'EG' },
	{ label: 'Сальвадор', code: 'SV' },
	{ label: 'Экваториальная Гвинея', code: 'GQ' },
	{ label: 'Эритрея', code: 'ER' },
	{ label: 'Эстония', code: 'EE' },
	{ label: 'Эсватини', code: 'SZ' },
	{ label: 'Эфиопия', code: 'ET' },
	{ label: 'Фолклендские Острова', code: 'FK' },
	{ label: 'Фарерские Острова', code: 'FO' },
	{ label: 'Фиджи', code: 'FJ' },
	{ label: 'Финляндия', code: 'FI' },
	{ label: 'Франция', code: 'FR' },
	{ label: 'Французская Гвиана', code: 'GF' },
	{ label: 'Французская Полинезия', code: 'PF' },
	{ label: 'Французские Южные Территории', code: 'TF' },
	{ label: 'Габон', code: 'GA' },
	{ label: 'Гамбия', code: 'GM' },
	{ label: 'Грузия', code: 'GE' },
	{ label: 'Германия', code: 'DE' },
	{ label: 'Гана', code: 'GH' },
	{ label: 'Гибралтар', code: 'GI' },
	{ label: 'Греция', code: 'GR' },
	{ label: 'Гренландия', code: 'GL' },
	{ label: 'Гренада', code: 'GD' },
	{ label: 'Гваделупа', code: 'GP' },
	{ label: 'Гуам', code: 'GU' },
	{ label: 'Гватемала', code: 'GT' },
	{ label: 'Гернси', code: 'GG' },
	{ label: 'Гвинея', code: 'GN' },
	{ label: 'Гвинея-Бисау', code: 'GW' },
	{ label: 'Гайана', code: 'GY' },
	{ label: 'Гаити', code: 'HT' },
	{ label: 'Острова Херд и Макдональд', code: 'HM' },
	{ label: 'Гондурас', code: 'HN' },
	{ label: 'Гонконг', code: 'HK' },
	{ label: 'Венгрия', code: 'HU' },
	{ label: 'Исландия', code: 'IS' },
	{ label: 'Индия', code: 'IN' },
	{ label: 'Индонезия', code: 'ID' },
	{ label: 'Иран', code: 'IR' },
	{ label: 'Ирак', code: 'IQ' },
	{ label: 'Ирландия', code: 'IE' },
	{ label: 'Остров Мэн', code: 'IM' },
	{ label: 'Израиль', code: 'IL' },
	{ label: 'Италия', code: 'IT' },
	{ label: 'Джерси', code: 'JE' },
	{ label: 'Иордания', code: 'JO' },
	{ label: 'Казахстан', code: 'KZ' },
	{ label: 'Кения', code: 'KE' },
	{ label: 'Кирибати', code: 'KI' },
	{ label: 'Северная Корея', code: 'KP' },
	{ label: 'Южная Корея', code: 'KR' },
	{ label: 'Кувейт', code: 'KW' },
	{ label: 'Киргизия', code: 'KG' },
	{ label: 'Лаос', code: 'LA' },
	{ label: 'Латвия', code: 'LV' },
	{ label: 'Ливан', code: 'LB' },
	{ label: 'Лесото', code: 'LS' },
	{ label: 'Либерия', code: 'LR' },
	{ label: 'Ливия', code: 'LY' },
	{ label: 'Лихтенштейн', code: 'LI' },
	{ label: 'Литва', code: 'LT' },
	{ label: 'Люксембург', code: 'LU' },
	{ label: 'Макао', code: 'MO' },
	{ label: 'Мадагаскар', code: 'MG' },
	{ label: 'Малави', code: 'MW' },
	{ label: 'Малайзия', code: 'MY' },
	{ label: 'Мали', code: 'ML' },
	{ label: 'Мальдивы', code: 'MV' },
	{ label: 'Мальта', code: 'MT' },
	{ label: 'Марокко', code: 'MA' },
	{ label: 'Мартиника', code: 'MQ' },
	{ label: 'Маршалловы Острова', code: 'MH' },
	{ label: 'Мавритания', code: 'MR' },
	{ label: 'Маврикий', code: 'MU' },
	{ label: 'Мексика', code: 'MX' },
	{ label: 'Микронезия', code: 'FM' },
	{ label: 'Молдова', code: 'MD' },
	{ label: 'Монако', code: 'MC' },
	{ label: 'Монголия', code: 'MN' },
	{ label: 'Монтсеррат', code: 'MS' },
	{ label: 'Мозамбик', code: 'MZ' },
	{ label: 'Мьянма', code: 'MM' },
	{ label: 'Намибия', code: 'NA' },
	{ label: 'Науру', code: 'NR' },
	{ label: 'Непал', code: 'NP' },
	{ label: 'Нигер', code: 'NE' },
	{ label: 'Нигерия', code: 'NG' },
	{ label: 'Нидерланды', code: 'NL' },
	{ label: 'Новая Каледония', code: 'NC' },
	{ label: 'Новая Зеландия', code: 'NZ' },
	{ label: 'Норвегия', code: 'NO' },
	{ label: 'Оман', code: 'OM' },
	{ label: 'Пакистан', code: 'PK' },
	{ label: 'Палау', code: 'PW' },
	{ label: 'Панама', code: 'PA' },
	{ label: 'Папуа — Новая Гвинея', code: 'PG' },
	{ label: 'Парагвай', code: 'PY' },
	{ label: 'Перу', code: 'PE' },
	{ label: 'Питкерн', code: 'PN' },
	{ label: 'Польша', code: 'PL' },
	{ label: 'Португалия', code: 'PT' },
	{ label: 'Пуэрто-Рико', code: 'PR' },
	{ label: 'Реюньон', code: 'RE' },
	{ label: 'Румыния', code: 'RO' },
	{ label: 'Россия', code: 'RU' },
	{ label: 'Руанда', code: 'RW' },
	{ label: 'Сент-Бартелеми', code: 'BL' },
	{ label: 'Сент-Евремонд', code: 'SH' },
	{ label: 'Сент-Люсия', code: 'LC' },
	{ label: 'Сент-Пьер и Микелон', code: 'PM' },
	{ label: 'Сент-Томас и Принсипи', code: 'ST' },
	{ label: 'Сенегал', code: 'SN' },
	{ label: 'Сен-Мартен', code: 'MF' },
	{ label: 'Сербия', code: 'RS' },
	{ label: 'Сингапур', code: 'SG' },
	{ label: 'Синт-Мартен', code: 'SX' },
	{ label: 'Сирия', code: 'SY' },
	{ label: 'Словакия', code: 'SK' },
	{ label: 'Словения', code: 'SI' },
	{ label: 'Соломоновы Острова', code: 'SB' },
	{ label: 'Сомали', code: 'SO' },
	{ label: 'Судан', code: 'SD' },
	{ label: 'Суринам', code: 'SR' },
	{ label: 'Сьерра-Леоне', code: 'SL' },
	{ label: 'Тайвань', code: 'TW' },
	{ label: 'Таджикистан', code: 'TJ' },
	{ label: 'Таиланд', code: 'TH' },
	{ label: 'Танзания', code: 'TZ' },
	{ label: 'Того', code: 'TG' },
	{ label: 'Токелау', code: 'TK' },
	{ label: 'Тонга', code: 'TO' },
	{ label: 'Тринидад и Тобаго', code: 'TT' },
	{ label: 'Тунис', code: 'TN' },
	{ label: 'Турция', code: 'TR' },
	{ label: 'Туркменистан', code: 'TM' },
	{ label: 'Тувалу', code: 'TV' },
	{ label: 'Уганда', code: 'UG' },
	{ label: 'Узбекистан', code: 'UZ' },
	{ label: 'Украина', code: 'UA' },
	{ label: 'Улыбка', code: 'UA' },
	{ label: 'Уоллис и Футуна', code: 'WF' },
	{ label: 'Уругвай', code: 'UY' },
	{ label: 'Французская Гвиана', code: 'GF' },
	{ label: 'Французская Полинезия', code: 'PF' },
	{ label: 'Французские Южные Территории', code: 'TF' },
	{ label: 'Габон', code: 'GA' },
	{ label: 'Гамбия', code: 'GM' },
	{ label: 'Грузия', code: 'GE' },
	{ label: 'Германия', code: 'DE' },
	{ label: 'Гана', code: 'GH' },
	{ label: 'Гибралтар', code: 'GI' },
	{ label: 'Греция', code: 'GR' },
	{ label: 'Гренландия', code: 'GL' },
	{ label: 'Гренада', code: 'GD' },
	{ label: 'Гваделупа', code: 'GP' },
	{ label: 'Гуам', code: 'GU' },
	{ label: 'Гватемала', code: 'GT' },
	{ label: 'Гернси', code: 'GG' },
	{ label: 'Гвинея', code: 'GN' },
	{ label: 'Гвинея-Бисау', code: 'GW' },
	{ label: 'Гайана', code: 'GY' },
	{ label: 'Гаити', code: 'HT' },
	{ label: 'Острова Херд и Макдональд', code: 'HM' },
	{ label: 'Гондурас', code: 'HN' },
	{ label: 'Гонконг', code: 'HK' },
	{ label: 'Венгрия', code: 'HU' },
	{ label: 'Исландия', code: 'IS' },
	{ label: 'Индия', code: 'IN' },
	{ label: 'Индонезия', code: 'ID' },
	{ label: 'Иран', code: 'IR' },
	{ label: 'Ирак', code: 'IQ' },
	{ label: 'Ирландия', code: 'IE' },
	{ label: 'Остров Мэн', code: 'IM' },
	{ label: 'Израиль', code: 'IL' },
	{ label: 'Италия', code: 'IT' },
	{ label: 'Джерси', code: 'JE' },
	{ label: 'Иордания', code: 'JO' },
	{ label: 'Казахстан', code: 'KZ' },
	{ label: 'Кения', code: 'KE' },
	{ label: 'Кирибати', code: 'KI' },
	{ label: 'Северная Корея', code: 'KP' },
	{ label: 'Южная Корея', code: 'KR' },
	{ label: 'Кувейт', code: 'KW' },
	{ label: 'Киргизия', code: 'KG' },
	{ label: 'Лаос', code: 'LA' },
	{ label: 'Латвия', code: 'LV' },
	{ label: 'Ливан', code: 'LB' },
	{ label: 'Лесото', code: 'LS' },
	{ label: 'Либерия', code: 'LR' },
	{ label: 'Ливия', code: 'LY' },
	{ label: 'Лихтенштейн', code: 'LI' },
	{ label: 'Люксембург', code: 'LU' },
	{ label: 'Мавритания', code: 'MR' },
	{ label: 'Маврикий', code: 'MU' },
	{ label: 'Мексика', code: 'MX' },
	{ label: 'Микронезия', code: 'FM' },
	{ label: 'Молдова', code: 'MD' },
	{ label: 'Монако', code: 'MC' },
	{ label: 'Монголия', code: 'MN' },
	{ label: 'Монтсеррат', code: 'MS' },
	{ label: 'Мозамбик', code: 'MZ' },
	{ label: 'Мьянма', code: 'MM' },
	{ label: 'Намибия', code: 'NA' },
	{ label: 'Науру', code: 'NR' },
	{ label: 'Непал', code: 'NP' },
	{ label: 'Нигер', code: 'NE' },
	{ label: 'Нигерия', code: 'NG' },
	{ label: 'Нидерланды', code: 'NL' },
	{ label: 'Новая Каледония', code: 'NC' },
	{ label: 'Новая Зеландия', code: 'NZ' },
	{ label: 'Норвегия', code: 'NO' },
	{ label: 'Оман', code: 'OM' },
	{ label: 'Пакистан', code: 'PK' },
	{ label: 'Палау', code: 'PW' },
	{ label: 'Панама', code: 'PA' },
	{ label: 'Папуа — Новая Гвинея', code: 'PG' },
	{ label: 'Парагвай', code: 'PY' },
	{ label: 'Перу', code: 'PE' },
	{ label: 'Питкерн', code: 'PN' },
	{ label: 'Польша', code: 'PL' },
	{ label: 'Португалия', code: 'PT' },
	{ label: 'Пуэрто-Рико', code: 'PR' },
	{ label: 'Реюньон', code: 'RE' },
	{ label: 'Румыния', code: 'RO' },
	{ label: 'Руанда', code: 'RW' },
	{ label: 'Сент-Бартелеми', code: 'BL' },
	{ label: 'Сент-Евремонд', code: 'SH' },
	{ label: 'Сент-Люсия', code: 'LC' },
	{ label: 'Сент-Пьер и Микелон', code: 'PM' },
	{ label: 'Сент-Томас и Принсипи', code: 'ST' },
	{ label: 'Сенегал', code: 'SN' },
	{ label: 'Сен-Мартен', code: 'MF' },
	{ label: 'Сербия', code: 'RS' },
	{ label: 'Сингапур', code: 'SG' },
	{ label: 'Синт-Мартен', code: 'SX' },
	{ label: 'Сирия', code: 'SY' },
	{ label: 'Словакия', code: 'SK' },
	{ label: 'Словения', code: 'SI' },
	{ label: 'Соломоновы Острова', code: 'SB' },
	{ label: 'Сомали', code: 'SO' },
	{ label: 'Судан', code: 'SD' },
	{ label: 'Суринам', code: 'SR' },
	{ label: 'Сьерра-Леоне', code: 'SL' },
	{ label: 'Тайвань', code: 'TW' },
	{ label: 'Таджикистан', code: 'TJ' },
	{ label: 'Таиланд', code: 'TH' },
	{ label: 'Танзания', code: 'TZ' },
	{ label: 'Того', code: 'TG' },
	{ label: 'Токелау', code: 'TK' },
	{ label: 'Тонга', code: 'TO' },
	{ label: 'Тринидад и Тобаго', code: 'TT' },
	{ label: 'Тунис', code: 'TN' },
	{ label: 'Турция', code: 'TR' },
	{ label: 'Туркменистан', code: 'TM' },
	{ label: 'Тувалу', code: 'TV' },
	{ label: 'Уганда', code: 'UG' },
	{ label: 'Узбекистан', code: 'UZ' },
	{ label: 'Украина', code: 'UA' },
	{ label: 'Улыбка', code: 'UA' },
	{ label: 'Уоллис и Футуна', code: 'WF' },
	{ label: 'Уругвай', code: 'UY' },
	{ label: 'Французская Гвиана', code: 'GF' },
	{ label: 'Французская Полинезия', code: 'PF' },
	{ label: 'Французские Южные Территории', code: 'TF' },
	{ label: 'Филиппины', code: 'PH' },
	{ label: 'Финляндия', code: 'FI' },
	{ label: 'Фиджи', code: 'FJ' },
	{ label: 'Хорватия', code: 'HR' },
	{ label: 'Центральноафриканская Республика', code: 'CF' },
	{ label: 'Чад', code: 'TD' },
	{ label: 'Чили', code: 'CL' },
	{ label: 'Швейцария', code: 'CH' },
	{ label: 'Швеция', code: 'SE' },
	{ label: 'Шпицберген и Ян Майен', code: 'SJ' },
	{ label: 'Южный Судан', code: 'SS' },
	{ label: 'Ямайка', code: 'JM' },
	{ label: 'Япония', code: 'JP' },
	{ label: 'США', code: 'US' },
	{ label: 'Великобритания', code: 'GB' }
]